package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (04/27/2019, 18:13) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("thin-server-client.xml")) {
            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: ProductCache");
            ignite.cache("ProductCache").loadCache(null);

            System.out.println(">>> Loading cache: ProductTagsCache");
            ignite.cache("ProductTagsCache").loadCache(null);

            System.out.println(">>> Loading cache: ProductTypeCache");
            ignite.cache("ProductTypeCache").loadCache(null);

            System.out.println(">>> Loading cache: PropertyCache");
            ignite.cache("PropertyCache").loadCache(null);

            System.out.println(">>> Loading cache: PropertyValueCache");
            ignite.cache("PropertyValueCache").loadCache(null);

            System.out.println(">>> Loading cache: TagCache");
            ignite.cache("TagCache").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}